### ISSUE TITLE
Example how to use Repo object

### ISSUE THREAD

**Issue by OmerHerera** [notatestuser/gift#61]
I want to use the Repo object to create a branch but it's not clear I  the README. 
What I need to require and how to initialize it. 
Thanks

**Comment by notatestuser** [comment]
Rather than instantiate a `Repo` directly you must use one of the methods listed [in the readme](https://github.com/notatestuser/gift/blob/6a59036f185b2d228466feb4d0a6a7a675e4522f/README.md#api) to get hold of one. Your options are to use an existing repository, initialise one, or clone from a remote.

**Comment by OmerHerera** [comment]
:+1: 
Thanks
 repo = require("gift")("repoName")
